# Generated by Django 5.0 on 2024-03-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0002_post_main_post_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
