# Generated by Django 5.0.7 on 2024-08-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0009_delete_question_delete_services_alter_post_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtube',
            name='video',
        ),
        migrations.AddField(
            model_name='youtube',
            name='video_url',
            field=models.URLField(default='http://example.com/default-video-url'),
        ),
    ]
