# Generated by Django 5.0 on 2024-03-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_youtube_status_alter_youtube_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='is_recent',
            field=models.BooleanField(default=False),
        ),
    ]
